# Generated by Django 5.1 on 2024-09-30 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_aplication', '0004_chat_project_milestone_reference_requirement_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='milestone',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='project',
        ),
        migrations.RemoveField(
            model_name='task',
            name='freelancer',
        ),
        migrations.DeleteModel(
            name='Milestone',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Requirement',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
