# Generated by Django 5.0.7 on 2024-10-22 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_aplication", "0004_chat_project_milestone_reference_requirement_task"),
        ("perfil", "0005_project_budget_project_deadline_project_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="milestone",
        ),
        migrations.AlterField(
            model_name="requirement",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="requirements",
                to="perfil.project",
            ),
        ),
        migrations.RemoveField(
            model_name="task",
            name="freelancer",
        ),
        migrations.AddField(
            model_name="application",
            name="accepted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="application",
            name="project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="applications",
                to="perfil.project",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="application",
            name="requirement",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="applications",
                to="my_aplication.requirement",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="application",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="requirement",
            name="description",
            field=models.CharField(default="No description provided.", max_length=500),
        ),
        migrations.AlterField(
            model_name="requirement",
            name="title",
            field=models.CharField(default="New Requirement", max_length=50),
        ),
        migrations.DeleteModel(
            name="Milestone",
        ),
        migrations.DeleteModel(
            name="Project",
        ),
        migrations.DeleteModel(
            name="Task",
        ),
    ]
