# Generated by Django 5.1 on 2024-09-25 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='jobs_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='price',
            field=models.CharField(max_length=100),
        ),
    ]
