# Generated by Django 5.1 on 2024-10-20 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_publication_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFreelancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(default='Description', max_length=500)),
                ('state', models.CharField(choices=[('PENDING', 'Finding freelancers'), ('IN_PROGRESS', 'Developing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=100)),
                ('project_picture', models.ImageField(blank=True, null=True, upload_to='project_pictures/')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='perfil.profile')),
            ],
        ),
    ]
