# Generated by Django 5.1 on 2024-10-20 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0003_projectfreelancer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('deadline', models.DateField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='milestones', to='perfil.projectfreelancer')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('deadline', models.DateField()),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='perfil.profile')),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='perfil.milestone')),
            ],
        ),
    ]
