# Generated by Django 5.1 on 2024-09-25 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0003_clientprofile_alter_content_profile_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentsClients', to='perfil.clientprofile')),
            ],
        ),
    ]
