# Generated by Django 5.0.7 on 2024-10-22 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perfil", "0004_commentclient"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="budget",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="project",
            name="deadline",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="description",
            field=models.CharField(default="No description provided.", max_length=500),
        ),
        migrations.AlterField(
            model_name="project",
            name="duration",
            field=models.CharField(default="Not Specified", max_length=100),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(default="Untitled Project", max_length=100),
        ),
        migrations.AlterField(
            model_name="project",
            name="type",
            field=models.CharField(default="General", max_length=100),
        ),
        migrations.AlterField(
            model_name="project",
            name="url",
            field=models.URLField(default="http://example.com"),
        ),
    ]
