# Generated by Django 5.1 on 2024-09-30 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0005_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
