# Generated by Django 5.1 on 2024-10-21 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0005_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialnetwork',
            name='client_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_social_networks', to='perfil.clientprofile'),
        ),
        migrations.AlterField(
            model_name='socialnetwork',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_networks', to='perfil.profile'),
        ),
    ]
