# Generated by Django 5.0.7 on 2024-10-22 07:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perfil", "0005_project_budget_project_deadline_project_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="date_created",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
