# Generated by Django 5.1 on 2024-10-21 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0006_socialnetwork_client_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='perfil.projectfreelancer'),
        ),
    ]
