# Generated by Django 5.0.7 on 2024-10-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perfil", "0007_project_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(default="No description provided."),
        ),
    ]
